import type { Metadata } from "next";
import { Geist, Geist_Mono, Onest } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import AppNavbar from "@/components/app-navbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                (function() {
                if(typeof window === "undefined") return;
                if (window.localStorage) {
                  try {
                    const stored = localStorage.getItem("theme");
                    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                    if (stored === "dark" || (!stored && prefersDark)) {
                      document.documentElement.classList.add("dark");
                    }
                  } catch (e) {}
                }
                })();
              `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${onest.className} antialiased`}
      >
        <Suspense>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="overflow-y-hidden">
              <AppNavbar />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </Suspense>
      </body>
    </html>
  );
}
